import type { TranscriptionExport, ExportFormat } from './types';
import { TranscriptionProcessor } from './transcriptionProcessor';

/**
 * Export transcription to Markdown format
 * Summary is prioritized at the top, full transcript at the bottom
 */
export function exportToMarkdown(data: TranscriptionExport): string {
  const { metadata, summary, segments } = data;

  // Format date
  const date = new Date(metadata.startTime).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const time = new Date(metadata.startTime).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });

  // Calculate stats
  const stats = TranscriptionProcessor.calculateStats(segments);
  const duration = TranscriptionProcessor.formatDuration(metadata.duration);

  let markdown = '';

  // Header
  markdown += '# Meeting Transcription\n\n';
  markdown += `**Date:** ${date} at ${time}  \n`;
  markdown += `**Duration:** ${duration}  \n`;
  markdown += `**Model:** ${metadata.whisperModel}  \n`;
  markdown += `**Language:** ${metadata.language}  \n`;
  markdown += `**Words:** ${stats.totalWords} (${stats.wordsPerMinute.toFixed(0)} WPM)  \n\n`;

  markdown += '---\n\n';

  // AI Summary (Priority Section)
  if (summary) {
    markdown += '## 📝 AI Summary\n\n';
    markdown += `${summary.text}\n\n`;

    if (summary.keyPoints && summary.keyPoints.length > 0) {
      markdown += '### Key Points\n\n';
      summary.keyPoints.forEach(point => {
        markdown += `- ${point}\n`;
      });
      markdown += '\n';
    }

    markdown += `*Generated by ${summary.model} on ${new Date(summary.generatedAt).toLocaleString()}*\n\n`;
    markdown += '---\n\n';
  }

  // Full Transcript
  markdown += '## 📄 Full Transcript\n\n';
  
  if (segments.length === 0) {
    markdown += '*No transcription available*\n';
  } else {
    const timestampedTranscript = TranscriptionProcessor.generateTimestampedTranscript(segments);
    markdown += timestampedTranscript + '\n';
  }

  markdown += '\n---\n\n';
  markdown += '*Transcribed with CipherDev - Privacy-First AI*\n';

  return markdown;
}

/**
 * Export transcription to JSON format
 */
export function exportToJSON(data: TranscriptionExport): string {
  return JSON.stringify(data, null, 2);
}

/**
 * Download file to user's device
 */
export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
): void {
  try {
    // Create blob
    const blob = new Blob([content], { type: mimeType });
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    
    // Trigger download
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    console.log('File downloaded:', filename);
  } catch (error) {
    console.error('Failed to download file:', error);
    throw new Error(
      `Failed to download file: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Generate filename for export
 */
export function generateFilename(format: ExportFormat, prefix: string = 'transcription'): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  const extension = format === 'markdown' ? 'md' : 'json';
  return `${prefix}_${timestamp}.${extension}`;
}

/**
 * Export transcription with automatic download
 */
export function exportTranscription(
  data: TranscriptionExport,
  format: ExportFormat = 'markdown'
): void {
  let content: string;
  let mimeType: string;

  if (format === 'markdown') {
    content = exportToMarkdown(data);
    mimeType = 'text/markdown';
  } else {
    content = exportToJSON(data);
    mimeType = 'application/json';
  }

  const filename = generateFilename(format);
  downloadFile(content, filename, mimeType);
}

/**
 * Copy transcription to clipboard
 */
export async function copyToClipboard(
  data: TranscriptionExport,
  format: ExportFormat = 'markdown'
): Promise<void> {
  try {
    const content = format === 'markdown' 
      ? exportToMarkdown(data)
      : exportToJSON(data);

    await navigator.clipboard.writeText(content);
    console.log('Copied to clipboard');
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    throw new Error(
      `Failed to copy to clipboard: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Get export preview (first 500 characters)
 */
export function getExportPreview(
  data: TranscriptionExport,
  format: ExportFormat = 'markdown',
  maxLength: number = 500
): string {
  const content = format === 'markdown' 
    ? exportToMarkdown(data)
    : exportToJSON(data);

  if (content.length <= maxLength) {
    return content;
  }

  return content.slice(0, maxLength) + '...';
}

// Made with Bob