/**
 * Languages supported by the Xenova Whisper ports we ship (whisper-tiny,
 * whisper-base, whisper-small — all v2 multilingual). 99 entries from the
 * official OpenAI Whisper tokenizer.
 *
 * `code` is the ISO 639-1 code used in metadata/exports.
 * `whisperName` is the lowercase English name the transformers.js pipeline
 * expects in the `language` option.
 */
export interface WhisperLanguage {
  code: string;
  whisperName: string;
  label: string;
}

export const WHISPER_LANGUAGES: WhisperLanguage[] = [
  { code: 'af', whisperName: 'afrikaans', label: 'Afrikaans' },
  { code: 'sq', whisperName: 'albanian', label: 'Albanian' },
  { code: 'am', whisperName: 'amharic', label: 'Amharic' },
  { code: 'ar', whisperName: 'arabic', label: 'Arabic (العربية)' },
  { code: 'hy', whisperName: 'armenian', label: 'Armenian' },
  { code: 'as', whisperName: 'assamese', label: 'Assamese' },
  { code: 'az', whisperName: 'azerbaijani', label: 'Azerbaijani' },
  { code: 'ba', whisperName: 'bashkir', label: 'Bashkir' },
  { code: 'eu', whisperName: 'basque', label: 'Basque' },
  { code: 'be', whisperName: 'belarusian', label: 'Belarusian' },
  { code: 'bn', whisperName: 'bengali', label: 'Bengali' },
  { code: 'bs', whisperName: 'bosnian', label: 'Bosnian' },
  { code: 'br', whisperName: 'breton', label: 'Breton' },
  { code: 'bg', whisperName: 'bulgarian', label: 'Bulgarian' },
  { code: 'my', whisperName: 'myanmar', label: 'Burmese / Myanmar' },
  { code: 'ca', whisperName: 'catalan', label: 'Catalan' },
  { code: 'zh', whisperName: 'chinese', label: 'Chinese (中文)' },
  { code: 'hr', whisperName: 'croatian', label: 'Croatian' },
  { code: 'cs', whisperName: 'czech', label: 'Czech' },
  { code: 'da', whisperName: 'danish' , label: 'Danish' },
  { code: 'nl', whisperName: 'dutch', label: 'Dutch (Nederlands)' },
  { code: 'en', whisperName: 'english', label: 'English' },
  { code: 'et', whisperName: 'estonian', label: 'Estonian' },
  { code: 'fo', whisperName: 'faroese', label: 'Faroese' },
  { code: 'fi', whisperName: 'finnish', label: 'Finnish (Suomi)' },
  { code: 'fr', whisperName: 'french', label: 'French (Français)' },
  { code: 'gl', whisperName: 'galician', label: 'Galician' },
  { code: 'ka', whisperName: 'georgian', label: 'Georgian' },
  { code: 'de', whisperName: 'german', label: 'German (Deutsch)' },
  { code: 'el', whisperName: 'greek', label: 'Greek (Ελληνικά)' },
  { code: 'gu', whisperName: 'gujarati', label: 'Gujarati' },
  { code: 'ht', whisperName: 'haitian creole', label: 'Haitian Creole' },
  { code: 'ha', whisperName: 'hausa', label: 'Hausa' },
  { code: 'haw', whisperName: 'hawaiian', label: 'Hawaiian' },
  { code: 'he', whisperName: 'hebrew', label: 'Hebrew (עברית)' },
  { code: 'hi', whisperName: 'hindi', label: 'Hindi (हिन्दी)' },
  { code: 'hu', whisperName: 'hungarian', label: 'Hungarian (Magyar)' },
  { code: 'is', whisperName: 'icelandic', label: 'Icelandic' },
  { code: 'id', whisperName: 'indonesian', label: 'Indonesian' },
  { code: 'it', whisperName: 'italian', label: 'Italian (Italiano)' },
  { code: 'ja', whisperName: 'japanese', label: 'Japanese (日本語)' },
  { code: 'jw', whisperName: 'javanese', label: 'Javanese' },
  { code: 'kn', whisperName: 'kannada', label: 'Kannada' },
  { code: 'kk', whisperName: 'kazakh', label: 'Kazakh' },
  { code: 'km', whisperName: 'khmer', label: 'Khmer' },
  { code: 'ko', whisperName: 'korean', label: 'Korean (한국어)' },
  { code: 'lo', whisperName: 'lao', label: 'Lao' },
  { code: 'la', whisperName: 'latin', label: 'Latin' },
  { code: 'lv', whisperName: 'latvian', label: 'Latvian' },
  { code: 'ln', whisperName: 'lingala', label: 'Lingala' },
  { code: 'lt', whisperName: 'lithuanian', label: 'Lithuanian' },
  { code: 'lb', whisperName: 'luxembourgish', label: 'Luxembourgish' },
  { code: 'mk', whisperName: 'macedonian', label: 'Macedonian' },
  { code: 'mg', whisperName: 'malagasy', label: 'Malagasy' },
  { code: 'ms', whisperName: 'malay', label: 'Malay' },
  { code: 'ml', whisperName: 'malayalam', label: 'Malayalam' },
  { code: 'mt', whisperName: 'maltese', label: 'Maltese' },
  { code: 'mi', whisperName: 'maori', label: 'Maori' },
  { code: 'mr', whisperName: 'marathi', label: 'Marathi' },
  { code: 'mn', whisperName: 'mongolian', label: 'Mongolian' },
  { code: 'ne', whisperName: 'nepali', label: 'Nepali' },
  { code: 'no', whisperName: 'norwegian', label: 'Norwegian' },
  { code: 'nn', whisperName: 'nynorsk', label: 'Norwegian Nynorsk' },
  { code: 'oc', whisperName: 'occitan', label: 'Occitan' },
  { code: 'ps', whisperName: 'pashto', label: 'Pashto' },
  { code: 'fa', whisperName: 'persian', label: 'Persian (فارسی)' },
  { code: 'pl', whisperName: 'polish', label: 'Polish (Polski)' },
  { code: 'pt', whisperName: 'portuguese', label: 'Portuguese (Português)' },
  { code: 'pa', whisperName: 'punjabi', label: 'Punjabi' },
  { code: 'ro', whisperName: 'romanian', label: 'Romanian (Română)' },
  { code: 'ru', whisperName: 'russian', label: 'Russian (Русский)' },
  { code: 'sa', whisperName: 'sanskrit', label: 'Sanskrit' },
  { code: 'sr', whisperName: 'serbian', label: 'Serbian' },
  { code: 'sn', whisperName: 'shona', label: 'Shona' },
  { code: 'sd', whisperName: 'sindhi', label: 'Sindhi' },
  { code: 'si', whisperName: 'sinhala', label: 'Sinhala' },
  { code: 'sk', whisperName: 'slovak', label: 'Slovak' },
  { code: 'sl', whisperName: 'slovenian', label: 'Slovenian' },
  { code: 'so', whisperName: 'somali', label: 'Somali' },
  { code: 'es', whisperName: 'spanish', label: 'Spanish (Español)' },
  { code: 'su', whisperName: 'sundanese', label: 'Sundanese' },
  { code: 'sw', whisperName: 'swahili', label: 'Swahili' },
  { code: 'sv', whisperName: 'swedish', label: 'Swedish (Svenska)' },
  { code: 'tl', whisperName: 'tagalog', label: 'Tagalog' },
  { code: 'tg', whisperName: 'tajik', label: 'Tajik' },
  { code: 'ta', whisperName: 'tamil', label: 'Tamil' },
  { code: 'tt', whisperName: 'tatar', label: 'Tatar' },
  { code: 'te', whisperName: 'telugu', label: 'Telugu' },
  { code: 'th', whisperName: 'thai', label: 'Thai (ไทย)' },
  { code: 'bo', whisperName: 'tibetan', label: 'Tibetan' },
  { code: 'tr', whisperName: 'turkish', label: 'Turkish (Türkçe)' },
  { code: 'tk', whisperName: 'turkmen', label: 'Turkmen' },
  { code: 'uk', whisperName: 'ukrainian', label: 'Ukrainian (Українська)' },
  { code: 'ur', whisperName: 'urdu', label: 'Urdu' },
  { code: 'uz', whisperName: 'uzbek', label: 'Uzbek' },
  { code: 'vi', whisperName: 'vietnamese', label: 'Vietnamese (Tiếng Việt)' },
  { code: 'cy', whisperName: 'welsh', label: 'Welsh' },
  { code: 'yi', whisperName: 'yiddish', label: 'Yiddish' },
  { code: 'yo', whisperName: 'yoruba', label: 'Yoruba' },
];

export const DEFAULT_WHISPER_LANGUAGE: WhisperLanguage = WHISPER_LANGUAGES.find(
  l => l.code === 'en',
)!;

export function getWhisperLanguageByCode(code: string): WhisperLanguage | undefined {
  return WHISPER_LANGUAGES.find(l => l.code === code);
}
