'use client';

import { Sparkles, RefreshCw } from 'lucide-react';
import type { TranscriptionSummary } from '@/features/transcription/types';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

interface SummaryCardProps {
  summary: TranscriptionSummary;
  isGenerating?: boolean;
  onRegenerate?: () => void;
  className?: string;
}

/**
 * AI-generated summary display card
 * Shows summary text, key points, and model attribution
 */
export function SummaryCard({
  summary,
  isGenerating = false,
  onRegenerate,
  className,
}: SummaryCardProps) {
  const formattedDate = new Date(summary.generatedAt).toLocaleString();

  return (
    <Card className={cn('p-6 space-y-4', className)} glow>
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-2">
          <div className="p-2 bg-blue-600/20 rounded-lg">
            <Sparkles className="h-5 w-5 text-blue-400" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-100">AI Summary</h3>
            <p className="text-xs text-gray-500">
              Generated by {summary.model}
            </p>
          </div>
        </div>

        {onRegenerate && (
          <Button
            variant="ghost"
            size="sm"
            onClick={onRegenerate}
            disabled={isGenerating}
            className="flex-shrink-0"
          >
            <RefreshCw className={cn('h-4 w-4 mr-2', isGenerating && 'animate-spin')} />
            Regenerate
          </Button>
        )}
      </div>

      {/* Summary text */}
      <div className="prose prose-invert max-w-none">
        <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
          {summary.text}
        </p>
      </div>

      {/* Key points */}
      {summary.keyPoints && summary.keyPoints.length > 0 && (
        <div className="space-y-2">
          <h4 className="text-sm font-semibold text-gray-400 uppercase tracking-wide">
            Key Points
          </h4>
          <ul className="space-y-2">
            {summary.keyPoints.map((point, index) => (
              <li
                key={index}
                className="flex items-start gap-3 text-gray-300"
              >
                <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-blue-600/20 text-blue-400 rounded-full text-xs font-medium mt-0.5">
                  {index + 1}
                </span>
                <span className="flex-1">{point}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Footer */}
      <div className="pt-4 border-t border-gray-800/50">
        <p className="text-xs text-gray-500">
          Generated on {formattedDate}
        </p>
      </div>

      {/* Loading state overlay */}
      {isGenerating && (
        <div className="absolute inset-0 bg-gray-900/80 backdrop-blur-sm rounded-lg flex items-center justify-center">
          <div className="text-center space-y-3">
            <div className="inline-block p-3 bg-blue-600/20 rounded-full">
              <Sparkles className="h-6 w-6 text-blue-400 animate-pulse" />
            </div>
            <p className="text-sm text-gray-300 font-medium">
              Generating summary...
            </p>
          </div>
        </div>
      )}
    </Card>
  );
}

// Made with Bob